initial version deployment yml
dilshan3/AzureCICDTest pull request #1
Opened 2022-08-10 12:11 UTC by Sahana-Sivaraj

2022-08-10 12:36 UTC, dilshan3 requested changes
The version should be '6.0'. Because, we are using the latest version

2022-08-11 05:17 UTC, Sahana-Sivaraj commented
> 

done the changes

2022-08-11 06:53 UTC, dilshan3 approved these changes

2022-08-11 06:54 UTC, dilshan3 approved these changes

2022-08-11 06:54 UTC, dilshan3 approved these changes

2022-08-11 06:55 UTC, merged